version: '3.4'

services:
  coverage:
    build:
      context: .
      dockerfile: Dockerfile.coverage
    environment:
      COVERALLS_REPO_TOKEN: "${COVERALLS_REPO_TOKEN}"
    volumes:
      - .:/src
    command: ./tests-coverage.sh

